[project]
name = "final-erp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-htmx>=1.27.0",
]

[dependency-groups]
dev = [
    "cookiecutter>=2.6.0",
]
